apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nextcloud"},"name":"nextcloud","namespace":"homelab-apps"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nextcloud"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"nextcloud"}},"spec":{"containers":[{"env":[{"name":"NEXTCLOUD_TRUSTED_DOMAINS","value":"nextcloud.home.arpa 192.168.88.12"},{"name":"NEXTCLOUD_OVERWRITEHOST","value":"nextcloud.home.arpa:8080"},{"name":"NEXTCLOUD_OVERWRITEPROTOCOL","value":"http"},{"name":"NEXTCLOUD_DATA_DIR","value":"/var/www/html/data"},{"name":"POSTGRES_DB","valueFrom":{"secretKeyRef":{"key":"POSTGRES_DB","name":"nextcloud-db-credentials"}}},{"name":"POSTGRES_USER","valueFrom":{"secretKeyRef":{"key":"POSTGRES_USER","name":"nextcloud-db-credentials"}}},{"name":"POSTGRES_PASSWORD","valueFrom":{"secretKeyRef":{"key":"POSTGRES_PASSWORD","name":"nextcloud-db-credentials"}}},{"name":"POSTGRES_HOST","value":"uranus-db-postgresql.uranus-db.svc.cluster.local"}],"image":"nextcloud:32-apache","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/status.php","port":"http"},"initialDelaySeconds":60,"periodSeconds":30},"name":"nextcloud","ports":[{"containerPort":80,"name":"http"}],"readinessProbe":{"httpGet":{"path":"/status.php","port":"http"},"initialDelaySeconds":60,"periodSeconds":20},"volumeMounts":[{"mountPath":"/var/www/html","name":"nextcloud-data"}]}],"volumes":[{"name":"nextcloud-data","persistentVolumeClaim":{"claimName":"nextcloud-pvc"}}]}}}}
    creationTimestamp: "2025-11-26T05:34:11Z"
    generation: 1
    labels:
      app: nextcloud
    name: nextcloud
    namespace: homelab-apps
    resourceVersion: "2307"
    uid: 62592b15-e78b-420e-bd1d-e95bb465e11d
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: nextcloud
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nextcloud
      spec:
        containers:
        - env:
          - name: NEXTCLOUD_TRUSTED_DOMAINS
            value: nextcloud.home.arpa 192.168.88.12
          - name: NEXTCLOUD_OVERWRITEHOST
            value: nextcloud.home.arpa:8080
          - name: NEXTCLOUD_OVERWRITEPROTOCOL
            value: http
          - name: NEXTCLOUD_DATA_DIR
            value: /var/www/html/data
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                key: POSTGRES_DB
                name: nextcloud-db-credentials
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: nextcloud-db-credentials
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: nextcloud-db-credentials
          - name: POSTGRES_HOST
            value: uranus-db-postgresql.uranus-db.svc.cluster.local
          image: nextcloud:32-apache
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /status.php
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: nextcloud
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /status.php
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/www/html
            name: nextcloud-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-pvc
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-11-26T05:35:51Z"
      lastUpdateTime: "2025-11-26T05:35:51Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-11-26T05:34:11Z"
      lastUpdateTime: "2025-11-26T05:35:51Z"
      message: ReplicaSet "nextcloud-594c9b7cf9" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"onlyoffice-docs","namespace":"homelab-apps"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"onlyoffice-docs"}},"template":{"metadata":{"labels":{"app":"onlyoffice-docs"}},"spec":{"containers":[{"env":[{"name":"JWT_ENABLED","value":"true"},{"name":"JWT_SECRET","valueFrom":{"secretKeyRef":{"key":"jwt-secret","name":"onlyoffice-jwt-secret"}}}],"image":"onlyoffice/documentserver:latest","imagePullPolicy":"IfNotPresent","name":"onlyoffice-docs","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"1","memory":"2Gi"},"requests":{"cpu":"250m","memory":"512Mi"}}}]}}}}
    creationTimestamp: "2025-11-26T05:24:21Z"
    generation: 3
    name: onlyoffice-docs
    namespace: homelab-apps
    resourceVersion: "48494"
    uid: b9158bbe-395c-48e8-8ad7-e14be3656289
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: onlyoffice-docs
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2025-11-26T21:00:44Z"
        creationTimestamp: null
        labels:
          app: onlyoffice-docs
      spec:
        containers:
        - env:
          - name: JWT_ENABLED
            value: "true"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                key: jwt-secret
                name: onlyoffice-jwt-secret
          image: onlyoffice/documentserver:latest
          imagePullPolicy: IfNotPresent
          name: onlyoffice-docs
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-11-26T21:00:46Z"
      lastUpdateTime: "2025-11-26T21:00:46Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-11-26T21:00:44Z"
      lastUpdateTime: "2025-11-26T21:00:46Z"
      message: ReplicaSet "onlyoffice-docs-7966bf7679" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 3
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
